#
# btop -- a resource monitor with a full-screen TUI, asked for alongside
# htop and screen for the jump box.
#
# Source is the upstream GitHub tag archive. btop publishes no source
# dist tarball -- its release assets are all PREBUILT musl binaries for
# ten architectures, and not one of them may be used here: the Build
# Provenance Mandate means everything Cix ships is built on a Cix host by
# Cix's own toolchain, so the only permissible input is the source. A tag
# archive is weaker provenance than a signed dist tarball (GitHub
# generates it on demand rather than serving a fixed published artifact),
# which is why pkg_sha256 below matters more here than usual: it pins the
# exact bytes regardless of what the endpoint decides to hand back.
#
pkg_name="btop"
pkg_version="1.4.7-1"
pkg_source="https://github.com/aristocratos/btop/archive/refs/tags/v1.4.7.tar.gz"
pkg_sha256="933de2e4d1b2211a638be463eb6e8616891bfba73aef5d38060bd8319baeefc6"
pkg_artifact_sha256="f7ad51f373152ee2af914320c8e4c0c32e50c46b3b498b3e23b24e8e2ad377f8"
#
# Nothing at runtime beyond libc. btop draws its own ANSI directly and
# links no curses at all -- it is not an ncurses program despite looking
# like one -- and libstdc++/libgcc are linked statically below, so this
# does not drag a C++ runtime into any image that installs it.
#
pkg_depends=""
#
# This is the first C++ package in this recipe set, so the toolchain
# declaration is doing real work rather than repeating a convention.
#
pkg_toolchain="gcc"
pkg_toolchain_reason="language: btop is C++ and its Makefile requires -std=c++23 (Makefile:173, override REQFLAGS). TCC is a C compiler and has no C++ front end at all, so this is not a TCC gap to be fixed or tracked -- it is the wrong tool. Measured against gcc 16.2.0, which implements C++23."
#
# ADR-0199/0209: the build environment is composed from exactly these and
# nothing else -- there is no fallback environment to inherit a missing
# tool from (#168). Each entry earns its place, and this Makefile shells
# out to more than most:
#   gcc         g++ and libstdc++; the compiler this package needs
#   make        drives the build
#   bash        pkg_build() runs under it
#   coreutils   head/cut/date/expr/tee/printf/cp/mkdir/chmod, all used by
#               the Makefile's own $(shell ...) calls and its install rule
#   findutils   the Makefile's own $(shell find ...) over src/
#   sed         the version header is generated by a sed substitution
#   grep        used throughout the Makefile's feature detection
#   glibc       getconf, which the Makefile calls for _NPROCESSORS_ONLN
#   binutils    ar/ranlib/ld for a real C++ link
#   linux-headers  kernel uapi headers, which glibc's own headers include
#
# Deliberately NOT declared: git. The Makefile calls it only to stamp a
# commit hash into its own version banner and tolerates its absence, so
# pulling git into every btop build to populate a cosmetic string would
# be a real cost for nothing. The banner reports an empty commit instead,
# which is honest -- this is not built from a git checkout.
#
# Sufficiency is enforced by the build itself. Minimality is review, not
# enforcement (ADR-0199).
pkg_build_depends="gcc make bash coreutils findutils sed grep glibc binutils linux-headers"
pkg_changelog="1.4.7-1: first packaging. C++23, built with gcc and linked against a static libstdc++/libgcc so no image installing it needs a C++ runtime."

pkg_build() {
	#
	# ADDFLAGS carries the two static-link flags rather than LDFLAGS
	# because this Makefile appends its own values to LDFLAGS after any
	# the environment sets, and appends ADDFLAGS last -- so ADDFLAGS is
	# the one that reliably reaches the link line.
	#
	# Static libstdc++ and libgcc are the whole reason btop needs no new
	# runtime package. The alternative is shipping the C++ runtime out of
	# the gcc package into every image that wants a process monitor,
	# which would put a compiler's output in a jump box to gain nothing:
	# one binary is the only consumer.
	#
	# GPU_SUPPORT=false: btop's GPU panels need NVIDIA/AMD/Intel vendor
	# libraries, none of which exist as a recipe here and none of which a
	# headless jump box has any use for. Disabled explicitly so it is a
	# decision rather than an accident of what happened to be present in
	# a given build container -- the same trap htop.recipe documents for
	# its own auto-detected features.
	#
	# VERBOSE=true so the real compile and link lines reach the build
	# log. This Makefile prints coloured progress instead of commands by
	# default, which is exactly what makes a failure here unreadable.
	#
	# /usr/bin/g++, never a bare `g++` off $PATH. Invoked by bare name,
	# a GCC driver computes its own installation prefix as a RELATIVE
	# path and then fails to find cc1plus, reporting it as
	# "posix_spawnp: No such file or directory" -- which reads as a
	# missing source file and is not. Same rule, same reason, as gcc
	# itself; see CLAUDE.md's environment notes.
	make CXX=/usr/bin/g++ VERBOSE=true GPU_SUPPORT=false STATIC=false \
	     ADDFLAGS="-static-libstdc++ -static-libgcc" \
	     -j"$(nproc)"

	#
	# Run what was built. btop is interactive, so --version is the honest
	# check available: it proves the binary links and starts. That matters
	# more than usual here -- a missing shared libstdc++ would not fail
	# the build, it would fail the first time an operator ran it.
	#
	out=$(./bin/btop --version 2>&1) || {
		echo "btop: the binary just built does not run:" >&2
		echo "$out" >&2
		exit 1
	}
	case "$out" in
	*1.4.7*) echo "  built btop runs: $out" ;;
	*)
		echo "btop: --version did not report the expected version, got: $out" >&2
		exit 1
		;;
	esac

	#
	# And prove the static link actually took. `ldd` on a correctly built
	# btop must not name libstdc++: if it does, the ADDFLAGS above did not
	# reach the link line and the binary will die on any image without a
	# C++ runtime -- which is every image this package is for. Checked
	# here rather than trusted, because the failure is silent at build
	# time and only appears on someone else's machine.
	#
	if ldd ./bin/btop 2>/dev/null | grep -q libstdc++; then
		echo "btop: linked against a SHARED libstdc++ -- the static flags did not apply:" >&2
		ldd ./bin/btop >&2
		exit 1
	fi
	echo "  confirmed: no shared libstdc++ dependency"
}

#
# The Makefile's own install rule, minus the desktop-integration files.
# A .desktop entry, a PNG and an SVG icon are for a graphical menu; this
# platform has no desktop and no image that installs btop has one either,
# so they would be dead weight in every rootfs. The themes ARE kept --
# btop reads them at runtime from usr/share/btop/themes and degrades to a
# single built-in theme without them.
#
pkg_install() {
	make DESTDIR="$PKG_DESTDIR" PREFIX=/usr install
	rm -rf "$PKG_DESTDIR/usr/share/applications"
	rm -rf "$PKG_DESTDIR/usr/share/icons"
	rm -rf "$PKG_DESTDIR/usr/share/doc"
}
