#
# gmp -- the GNU Multiple Precision arithmetic library.
#
# Packaged for one reason: nftables (the nft CLI, a different upstream
# project from libnftnl) requires it outright --
# `AC_CHECK_LIB([gmp],[__gmpz_init], , AC_MSG_ERROR([No suitable
# version of libgmp found]))`. That is a hard requirement, not a probe,
# so nftables cannot be built at all without this.
#
# Source is gmplib.org's own release archive. Checksum computed
# directly from the downloaded bytes.
#
# THE INTERESTING QUESTION HERE IS WHETHER TCC CAN BUILD IT.
#
# GMP names six of the builtins TCC does not implement (#208):
# __builtin_ctzl, __builtin_ctzll, __builtin_clzl, __builtin_clzll,
# __builtin_ffs and __builtin_add_overflow. Read against the source
# rather than assumed, that turns out not to matter:
#
#   * longlong.h's uses are inside MACRO DEFINITIONS
#     (count_leading_zeros_gcc_clz, count_trailing_zeros_gcc_ctz), and
#     those macros are only ever INVOKED from the per-CPU blocks
#     further down, every one of which sits inside
#     `#if defined (__GNUC__)`. TCC does not define __GNUC__, so the
#     macros are defined and never expanded, and GMP falls back to its
#     own generic C implementations. A macro that is never expanded
#     costs nothing.
#
#   * __builtin_add_overflow appears only in mpn/s390_64/, which is not
#     compiled on x86-64.
#
#   * gmpxx.h is C++ and needs --enable-cxx, which is off by default.
#
# --disable-assembly is the load-bearing flag: GMP's x86-64 paths are
# GNU inline assembly, which TCC cannot compile. The generic C code is
# slower and is the same arithmetic. Correctness is what nftables needs
# from this; nothing here is on a hot path.
#
pkg_name="gmp"
pkg_version="6.3.0-2"
pkg_source="https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz"
pkg_sha256="a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898"
pkg_artifact_sha256="cadb0a54d9946b139986943c5871fff264e78b1ba72cc78c6cafefa9edabe990"
pkg_depends=""
#
# m4 is real here, not defensive: GMP's build generates code with it
# even in a generic build, and its configure looks for it by name.
#
pkg_build_depends="tcc make linux-headers bash coreutils sed grep gawk binutils findutils diffutils m4"
pkg_changelog="6.3.0-2: rebuilt against tcc 0.9.28rc (ADR-0223). The 2017 0.9.27 release could give two simultaneously-live locals the same stack slot (#216), a fault that corrupts values silently wherever the aliased pair is only read and written, so every binary it produced is suspect rather than merely the ones that failed. No source change: the revision exists to make the rebuild real, because an image version is a hash of the package manifest (ADR-0155) and a same-version reinstall is deduped and discarded. 6.3.0: first packaging -- required outright by nftables, which errors out without libgmp. Built with --disable-assembly since GMP's x86-64 paths are GNU inline assembly TCC cannot compile; the generic C fallback is the same arithmetic (#207)"

pkg_build() {
	#
	# CC=tcc is pinned explicitly rather than left to configure's own
	# compiler search. GMP does its own CC selection before AC_PROG_CC
	# and is unusually opinionated about it, and this build sandbox's
	# bare 'cc' can no longer be trusted to mean TCC (see CLAUDE.md).
	#
	CC=tcc ./configure --prefix=/usr --disable-assembly --disable-static

	echo "=== what configure decided ==="
	grep -E "^(CC|ABI|GMP_LIMB_BITS|host) " config.log 2>/dev/null | head -6 || true

	make -j"$(nproc)"
}

pkg_install() {
	make install DESTDIR="$PKG_DESTDIR"

	rm -rf "$PKG_DESTDIR/usr/share/info" "$PKG_DESTDIR/usr/share/man"
	rm -f "$PKG_DESTDIR"/usr/lib/*.la

	echo "=== what shipped ==="
	find "$PKG_DESTDIR" -name 'libgmp*' -o -name 'gmp.h' -o -name '*.pc' \
	    | sed "s|$PKG_DESTDIR||" | sort

	#
	# A shared library must exist: nftables links against it, and a
	# static-only build would install cleanly and fail nftables'
	# AC_CHECK_LIB much later, blaming gmp for being absent when it is
	# present (#113).
	#
	ls "$PKG_DESTDIR"/usr/lib/libgmp.so.* >/dev/null 2>&1 || {
		echo "no shared libgmp was built" >&2
		exit 1
	}
	test -e "$PKG_DESTDIR/usr/include/gmp.h" || {
		echo "gmp.h missing" >&2
		exit 1
	}

	# gmp.pc is generated by configure and describes exactly the header
	# and library above, so it is a true claim and ships. nftables does
	# not use it -- it uses AC_CHECK_LIB -- but other consumers do.
	test -e "$PKG_DESTDIR/usr/lib/pkgconfig/gmp.pc" || {
		echo "gmp.pc missing" >&2
		exit 1
	}

	echo "=== libgmp DT_NEEDED ==="
	readelf -d "$PKG_DESTDIR"/usr/lib/libgmp.so.* | grep NEEDED || true
}
