#
# kernel-builder -- one job: build the Linux kernel and its modules via
# `pkg hostbuild kernel` (and `cixctl kmod-build`, which is the same
# call with extra CONFIG_ symbols). ADR-0208.
#
# This exists because the kernel guide used to say --build-image=dev,
# and `dev` carried neither gcc nor kmod -- so the documented
# self-hosted kernel build could not work as written. Rather than
# quietly widening a general-purpose image until it happened to
# suffice, the kernel gets an image named for the job, holding exactly
# what kernel.recipe actually invokes.
#
# Every entry traces to a real invocation in that recipe:
#   gcc       the kernel is built with a real GCC toolchain
#             (HOSTCC=/usr/bin/gcc CC=/usr/bin/gcc) -- unmodified
#             upstream software this platform runs, not this project's
#             own code, so ADR-0001's TCC mandate does not apply to it.
#             This is the ONE build image that legitimately holds gcc.
#   binutils  as/ld/ar, which every kernel link goes through
#   kmod      the `depmod -b` that ends pkg_install(); without it the
#             artifact has modules but no modules.dep, and cixd's own
#             boot-time modprobe (ADR-0061) has nothing usable to read
#   make      drives the whole build
#   bc        kernel/timeconst.h is generated by a bc script
#   bison,flex  the kconfig parser is generated with them
#   elfutils  libelf, required by CONFIG_UNWINDER_ORC's objtool
#   libc-dev  headers + CRT for the HOSTCC-compiled tooling
#   bash,coreutils,sed,grep,gawk,tar,xz,zlib  the shell and text tools
#             the kernel's own scripts/ and Makefiles shell out to
#
# NOT PUBLISHED. It was built on 192.168.15.95 and published, then
# withdrawn the same day: its /usr/include is the build container's
# entire /usr/include, copied wholesale by libc-dev.recipe
# (`cp -a /usr/include/.`), so the artifact carried Debian's own
# Erlang, valgrind and gcc-12 C++ headers. Built on a Cix host, yes --
# but containing another operating system's files, which the Build
# Provenance Mandate forbids just as plainly. See issue #169.
#
# image_artifact_sha256 goes back only once the content is genuinely
# ours. That line approves a specific byte sequence, and these bytes
# should not be approved.
#
image_packages="bash:pinned:5.2.37-2 bc:pinned:1.08.1-2 binutils:pinned:2.42-8 bison:pinned:3.8.2-2 bzip2:pinned:1.0.8 coreutils:pinned:9.11-3 elfutils:pinned:0.192-8 flex:pinned:2.6.4-4 gawk:pinned:5.3.0-2 gcc:pinned:16.2.0-11 grep:pinned:3.11-4 kmod:pinned:34.2-2 libc-dev:pinned:2.36-5 m4:pinned:1.4.19-2 make:pinned:4.4.1-4 sed:pinned:4.9-2 tar:pinned:1.35-5 xz:pinned:5.8.3-4 zlib:pinned:1.3.2-6"
