#
# 1.5.0: wireless-regdb, because the regulatory database is now built
# INTO the kernel rather than loaded from disk (#342).
#
# cfg80211 is built in and asks for regulatory.db during its own init,
# which on this platform is before any root filesystem is mounted --
# measured on a real boot:
#
#   faux_driver regulatory: Direct firmware load for regulatory.db failed with error -2
#   cfg80211: failed to load regulatory.db
#
# rtw88's own blob loads fine from the same /lib/firmware seconds later,
# because a USB probe happens after root is up. So this is timing, not
# staging, and no amount of putting the file on disk fixes it. The fix
# is CONFIG_EXTRA_FIRMWARE, which copies the file into the kernel image
# at BUILD time -- and that requires the file to be present in this
# build image, at CONFIG_EXTRA_FIRMWARE_DIR.
#
# In the image and not the kernel recipe's pkg_build_depends, for the
# reason ADR-0199 now records: a host build's sandbox IS this image's
# rootfs, and build_depends composes nothing there. openssl (1.3.0) and
# perl (1.4.0) are both here for exactly the same reason, and both were
# found the same way -- by a kernel build failing on a missing tool.
#
#
# 1.4.0: perl, because a signed regulatory database needs an OID
# registry and the OID registry is generated by a Perl script (#30).
#
# The build reached lib/ -- past the certs/ failure 1.3.0 fixed -- and
# died with:
#
#   GEN     lib/oid_registry_data.c
#   /usr/bin/bash: line 1: perl: command not found
#   make[3]: *** [lib/Makefile:295: lib/oid_registry_data.c] Error 127
#
# lib/build_OID_registry is a Perl script, and the OID registry is
# reached from asymmetric key parsing, which is reached from
# SYSTEM_DATA_VERIFICATION -- the same symbol
# CFG80211_REQUIRE_SIGNED_REGDB selects and the same one that pulled in
# openssl at 1.3.0. One config change, two build dependencies, arriving
# a build apart.
#
# This file's own 1.0.3 header explicitly considered perl and ruled it
# out: "perl is only reached through recordmcount.pl (ftrace, off under
# allnoconfig)". That was a careful reading of the build machinery and
# it was measurably incomplete, in exactly the way 1.3.0 already warned
# about in writing -- what a kernel build needs is a function of the
# CONFIG it is given, not only of the source tree. The warning was
# written and the next dependency still arrived unannounced, which is
# the honest lesson: reading Makefiles predicts what a build reaches
# for less reliably than building it does.
#
# Nothing else changes. Every other pin is 1.3.0's.
#
#
# 1.2.0: gcc 16.2.0-11 -> 16.2.0-13. The pinned gcc had become
# uninstallable, and the failure named the wrong package.
#
#   POST /v1/pkg/install {"name":"gcc","version":"16.2.0-11", ...}
#   -> 400 {"error":"no such recipe, or it failed to parse"}
#
# gcc 16.2.0-11 is present in the catalogue and parses fine. What does
# not resolve is its own `pkg_depends="binutils m4 zlib libc-dev"`:
# libc-dev was retired by ADR-0217 phase 3 in favour of linux-headers,
# and gcc moved to it at 16.2.0-12. So -11 is the last gcc that still
# names a package which no longer exists anywhere -- confirmed by
# reading the catalogue (`libc-dev` returns zero versions) rather than
# inferred from the message, which blames gcc.
#
# This manifest already made that same move for itself at 1.1.0
# (libc-dev -> glibc) and simply did not carry it into the gcc pin.
#
# 16.2.0-13 rather than the newest (-16) deliberately: -13 is in the
# artifact cache at 436.4 MiB and is what cix-builder on 192.168.15.95
# already runs, so this is an install rather than a multi-hour gcc
# source build. -14..-16 would each need building first, which is real
# cost for no benefit to what this image does.
#
#
# 1.1.0: libc-dev -> glibc (#187, ADR-0217). Same job, different
# provider: libc-dev was Debian headers and CRT objects repackaged;
# glibc is the one this project builds from source (ADR-0216) and
# carries the same headers and the same crt1.o/crti.o/crtn.o. Pinned
# at 2.44-12, the revision every live builder on 192.168.15.95 already
# runs. Named explicitly because glibc is implicit only for a composed
# build environment (PKG_BASE_LIBC) and for the default image -- a
# named image gets exactly what its manifest names.
#
#
# kernel-builder -- one job: build the Linux kernel and its modules via
# `pkg hostbuild kernel` (and `cixctl kmod-build`, which is the same
# call with extra CONFIG_ symbols). ADR-0208.
#
# This exists because the kernel guide used to say --build-image=dev,
# and `dev` carried neither gcc nor kmod -- so the documented
# self-hosted kernel build could not work as written. Rather than
# quietly widening a general-purpose image until it happened to
# suffice, the kernel gets an image named for the job, holding exactly
# what kernel.recipe actually invokes.
#
# Every entry traces to a real invocation in that recipe:
#   gcc       the kernel is built with a real GCC toolchain
#             (HOSTCC=/usr/bin/gcc CC=/usr/bin/gcc) -- unmodified
#             upstream software this platform runs, not this project's
#             own code, so ADR-0001's TCC mandate does not apply to it.
#             This is the ONE build image that legitimately holds gcc.
#   binutils  as/ld/ar, which every kernel link goes through
#   kmod      the `depmod -b` that ends pkg_install(); without it the
#             artifact has modules but no modules.dep, and cixd's own
#             boot-time modprobe (ADR-0061) has nothing usable to read
#   make      drives the whole build
#   bc        kernel/timeconst.h is generated by a bc script
#   bison,flex  the kconfig parser is generated with them
#   elfutils  libelf, required by CONFIG_UNWINDER_ORC's objtool
#   glibc     headers + CRT for the HOSTCC-compiled tooling (was
#             libc-dev until 1.1.0 -- see this file's own header)
#   bash,coreutils,sed,grep,gawk,tar,xz,zlib  the shell and text tools
#             the kernel's own scripts/ and Makefiles shell out to
#
# NOT PUBLISHED. It was built on 192.168.15.95 and published, then
# withdrawn the same day: its /usr/include is the build container's
# entire /usr/include, copied wholesale by libc-dev.recipe
# (`cp -a /usr/include/.`), so the artifact carried Debian's own
# Erlang, valgrind and gcc-12 C++ headers. Built on a Cix host, yes --
# but containing another operating system's files, which the Build
# Provenance Mandate forbids just as plainly. See issue #169.
#
# The withdrawn artifact is not coming back in any form: ADR-0209
# retired whole-rootfs image artifacts entirely, so there is no longer
# a byte sequence at this layer to approve. Each package below installs
# from its own individually checksummed artifact instead.
#
# 1.0.1: two pins named versions that do not exist in the artifact
# cache, so this manifest could not be satisfied at all.
#
#   libc-dev 2.36-6  declared but never built. Under composed build
#                    environments (ADR-0199) it could not be: its build
#                    container has no glibc headers, and both halves of
#                    that recipe read them. What used to supply them was
#                    the shared sandbox holding the build host's entire
#                    /usr -- the very thing #168 removed. Fixed by
#                    libc-dev naming its own predecessor as a build
#                    input (2.36-7), then by reading the archives from
#                    /lib/x86_64-linux-gnu rather than the /usr/lib
#                    spelling that only ever resolved because Debian's
#                    usrmerge made them the same file (2.36-8).
#   elfutils 0.192-8 declared no pkg_build_depends at all, so it failed
#                    before fetching a byte (#168 has no fallback).
#                    0.192-9 declares them.
#
# Both are now built and published, so this manifest is satisfiable for
# the first time. 2.36-8 is also the decontaminated libc-dev #169 asked
# for -- 1,424 files with zero foreign headers, against 6,123 before --
# which is what got the previous kernel-builder artifact withdrawn.
# 1.0.2: gawk 5.3.0-7, not 5.3.0-2. The kernel build reached real code
# generation and then died with
#
#   awk: error while loading shared libraries: libtinfo.so.6:
#        cannot open shared object file: No such file or directory
#   make[1]: *** [arch/x86/Makefile:276: ... cpufeaturemasks.h] Error 127
#
# gawk 5.3.0-2 links libreadline.so.8, which pulls libtinfo, and neither
# is in this image -- confirmed by reading DT_NEEDED off both published
# artifacts rather than inferring it:
#   5.3.0-2  libreadline.so.8  libc.so.6  libm.so.6
#   5.3.0-7  libm.so.6  libc.so.6
# 5.3.0-5..-7 are the revisions that stopped gawk shipping and linking
# the build host's Debian libreadline, so pinning -7 both fixes the
# build and removes a foreign library from this image's closure.
#
# The whole image was then swept the same way -- every NEEDED entry of
# every binary in every installed package, checked against what the
# image actually provides -- and libtinfo was the only real gap.
# 1.0.3: findutils, gzip and diffutils. The build got as far as
# compiling real kernel objects and then died on every archive step:
#
#   /usr/bin/bash: line 1: xargs: command not found
#   make[4]: *** [scripts/Makefile.build:473:
#                 arch/x86/boot/startup/built-in.a] Error 127
#
# Rather than add xargs and rediscover the next one a build at a time,
# the kernel's own build machinery was read: every external command
# named by the top-level Makefile, scripts/Makefile.build,
# Makefile.lib, link-vmlinux.sh and arch/x86's Makefiles, checked
# against what this image holds.
#
#   findutils  xargs, unconditionally, in cmd_ar_builtin -- the rule
#              that creates built-in.a in EVERY directory. Not an edge
#              case; the build cannot link anything without it.
#   gzip       scripts/Makefile.lib's compression rules. allnoconfig
#              takes the first entry of the kernel-compression choice,
#              which is CONFIG_KERNEL_GZIP.
#   diffutils  `cmp -s System.map` in link-vmlinux.sh's kallsyms pass.
#
# Deliberately NOT added, having checked where each actually appears:
# perl is only reached through recordmcount.pl (ftrace, off under
# allnoconfig); python3, rsync and patch occur only in top-level
# targets this build never invokes; zstd only under CONFIG_KERNEL_ZSTD;
# bc is not on the bzImage path at all.
#
# openssl (1.3.0, #30) is the exception that proves the reading above
# was incomplete rather than wrong. It is not reached from any of those
# Makefiles: it is pulled in by the CONFIG, not by the build machinery.
# Enabling wireless enabled CFG80211_REQUIRE_SIGNED_REGDB -- which
# cannot be turned off, its prompt being conditional on
# CFG80211_CERTIFICATION_ONUS -- and that selects
# SYSTEM_DATA_VERIFICATION, which builds certs/extract-cert, a HOST
# tool that includes <openssl/bio.h>. Three kernel builds died there
# before the cause was measured rather than reasoned about
# (probe-wifi-driver/4).
#
# The lesson for this file: what a kernel build needs is a function of
# the config it is given, not only of the source tree. A config change
# can add a build dependency without a single line of the build
# machinery changing.
#
# It also explains a trap worth naming, because it cost a whole build:
# the kernel recipe's own pkg_build_depends is a DESCRIPTION of what
# this image must contain, not an instruction to install anything.
# Adding "openssl" there and rebuilding the kernel changed nothing at
# all -- the build container is composed from this image, and this
# image is what has to gain the package.
image_packages="wireless-regdb:pinned:2026.09.03-2 perl:pinned:5.40.1-7 bash:pinned:5.2.37-2 bc:pinned:1.08.1-2 binutils:pinned:2.42-8 bison:pinned:3.8.2-2 diffutils:pinned:3.10-6 bzip2:pinned:1.0.8 coreutils:pinned:9.11-3 elfutils:pinned:0.192-9 findutils:pinned:4.10.0-4 flex:pinned:2.6.4-4 gawk:pinned:5.3.0-7 gcc:pinned:16.2.0-13 grep:pinned:3.11-4 gzip:pinned:1.13-3 kmod:pinned:34.2-2 glibc:pinned:2.44-12 m4:pinned:1.4.19-2 make:pinned:4.4.1-4 sed:pinned:4.9-2 tar:pinned:1.35-5 xz:pinned:5.8.3-4 zlib:pinned:1.3.2-6 openssl:pinned:3.0.20-6"
